{% set version = "1.3.0" %}

package:
  name: libkml
  version: {{ version }}

source:
  fn: libkml-{{ version }}.tar.gz
  url: https://github.com/libkml/libkml/archive/{{ version }}.tar.gz
  sha256: 8892439e5570091965aaffe30b08631fdf7ca7f81f6495b4648f0950d7ea7963
  patches:
    # Patches for vc14. If this works we should wrapit in a ifdef and send the patch upstream.
    - empty_char.patch  # [win and (py35 or py36)]

build:
  number: 0
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - cmake
    - python  # [win]
    - expat 2.1.*
    - zlib 1.2.*
    - boost 1.64.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
  run:
    - expat 2.1.*
    - zlib 1.2.*
    - boost 1.64.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    - test -f $PREFIX/lib/libkmlbase.so.1  # [linux]
    - test -f $PREFIX/lib/libkmlbase.dylib  # [osx]
    - if not exist %LIBRARY_LIB%\\kmlbase.lib exit 1  # [win]
    - conda inspect linkages -p $PREFIX libkml  # [not win]
    - conda inspect objects -p $PREFIX libkml  # [osx]

about:
  home: https://github.com/libkml/libkml
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Reference implementation of OGC KML 2.2'
  description: |
    This is Google's reference implementation of OGC KML 2.2.
    It also includes implementations of Google's gx: extensions used by Google Earth,
    as well as several utility libraries for working with other formats.

extra:
  recipe-maintainers:
    - ocefpaf
