# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PVQ22sDp6W0+WtjprJn035Jz2cKBzScFbtiKjrQuPreggYx2SCp7OckM28rn+JPs6AMefJfBDLDDqLMfCRO575Nplm8txI7pbEl33IiJbLWmp9NbjJUgsmecM8BZ5YNt7ym1owbgDLU0beEZbpaPsvc7pJPnP9sBPavF8NIGmPOs/kmRFTVRuyy0/KgX8XyR0Mk19ngJ9Sm/OTx/jEb1JKPEYnu1j9dIz4FXnes0hvUT7fqrQXOQWBrnhTEHWgWynwMN1b1dr4Q1l87ZF33FhAcdjjGCZ9gzxdP7nb8WTO3piHi15cpg444fwyY9uQI+97LxMpkUjd/9+o9AjKUFhpjhzoSA4KdS8pmLO/Ua2Ks+9/1nRGl2R/0hh5hxChySLQZkqRAvF5YmVtMxnQTaOg6s7xBshMklWyoo498whSL4SHhgq7jwTstdUmn4ngsz4fRQCDkTTGJz6JZNyCgl9951hHmjFaUJSN84cJ/9m63zgTW3TdpRf5xiuFRRjRP+2ByZHcRuR94Qt7pzkvCd4OP5OXzm+cfNEJGHsDUbzAhKiah8NbM8c5WjzCW9WmBQ0Tx/4ZKAwXE8DJtH9BbH3AfSsi3O3rmT3bxIAuksRfZe0ijevbL9DTN9rOmeDejA2NIwzJREu51C4D2iaC2zNkh7C+3oL1UNK2hvBJO6z28="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
