# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "uONLOH6igWVdaGmDBePkXM0P/pMtwLLWQRUKKKjzJ4jK53RDGKHDoFlvimOcajP/r0WKdhqOZMSMvQMNrRKBLeWFuTgTIwcf4Sz/tQ4x7ZDJ7O52I0YvtLSmchZrzP+uFJ+ciQBtwB7L2tr3AgFiE86Widpcicq0tYhmV7po/L9gqxMwt0oiRhM7++DkTpfbBqcPLPwIxlfcAW1JZvsrNLNGonoVlnd3GLs+C91edrhLd0d140nPWVW3zy2jM7TYyOmUFNvT5a6H9BKBDjpRksh0LR+5ypts5FmeZQXm8f5khd+bIiX2WwqsQeGlwPAoaTqrmSDYiG1ADbtkUmk4NFaVHsV9jsabzla6vSW1kcMgtVuuyipBnzfZ66h4e4OhQodGYot2m1GrSOMuqNj4sY/ZjC/P+jx8i/Y6127lKZsOqZVo1U30QJjoTfNMIJBafK+w97lLWEa8jVEogemo+9VxVpZf5pQhJ5TGkc+fUqWnvDyb6/4thSmqCJhhH+fU77K1h3NZ3PgBfkvzoIpzl7OyVb000Qk9dq0We0PNRkO5qcjnmvdgLLSi7DlcgZ0NQZH5gJFwCmrDKP55xn9freIWgPhuJ+J56iyqO/DHxmvxMtcwrcB9Ieltab43vxXjUK5awdCqUxzB4FZNCOaZu3mrbfcJHc2X63ce5qpwGbk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
