travis:
  secure:
    BINSTAR_TOKEN: v1+bhDznab751NxXdjFWc1XSbSIpiTvUA+xoDpYdyL+i8lXRJbr7sJ5MkMTp56d2lBZfkG8h4t1bT5XiOBB9TYD3hAX7TsdBfBbEYciBYOjObtPJQpNtchdTQpsel/mkVbguAYybdNVMGQGD6ZtRiL4dpaLokvriCr75Yg4FkPL6lw+iqGFQyRRn9MHMGwjmfg8eVFqZzNimC13HSMSk+Yk/ZMCzfcgznno1w5wkVqlx7htwY9GUt4F3+KWVzBNqw5i+0ykQagrb3osko/wk1A1QBuMlB4Pvyj4gOdDnwAx9G/uOzHz2aByiaufqyNkojQsf1gd6FIbgzl3xFHYOPzuK+YB+Wb5nR6TdALHIxB+YJcgw3+zsOWYJ7W6h7epsxnI6/a1CiP+pXDu1pjVmrdVzyce2dSfiILVLKXfMgPnnmyGQl+QEZE5lndDfL8Jp2F2u+5oog5HJFEkf4kIMxiEEfMrsVdWDb1e2c/NLj/VwbrLjtZhbAN1bTAfwGN0gkBS4tYE4vQoavPf4/CR4sHfJFXmCIY+H7XHJe6eHVOaT7Sy5JbyIetHYgfSk2Fstu401fQK2QzHZtI12Oan/jkohqIhS4eATaiWKPOi3d2kSOSMFpEZLE1wDwPwks9qGARLY8HHIsfDA7ZzTfZMVbrN8yH1PhBA2XE1rtkmN0dE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
