travis:
  secure:
    BINSTAR_TOKEN: Sr2GxihpTEYf6PudZa3SIBbMFzRn4aK88C6OEsETxgohnfeemxkDBBAkUclBRNeTkMo3mBQ+NHrexakfP1bwNmG/A6VObFeoSU+l6RauvwFUNaFMaXlygs5rjdS84F+pYpeAmpg3LIDvZRo5bFlCmnv9ddy1pVpAt+Lxy0uCGLpUiwxHx1QOHJl1WGuY6726CpHX9t8H9FObPgD0epZp5KvQZ07cyZEATxAMU1GX2skcud9+7RJyuoza3VJYH6gsC0N9q22qDVzfB+nmhr6O9QsnHzBSW7CplRcxoI7nKEX1WAGtEumoj54Aux6ljBJN2bgT2BXef/SA+dnpfbMFpLc0K8sFYQkBk0kG68EL3nqswekTjikZXmV/vFRrzY5GKIGgLZpNYUQR625CS2mY/rals/W8rtQY21o3CIIBvBrDSvfO9bF/yzIO/+OQ636SebiuA4o7Lkc+cPcXFxIOTUNxi8Cxw0EtmeRijlQk2fTuhvytoMzQyYjlYsMIFSFJSoQaQrwZszG+ejYKv6Qn/GYqda207faGvVNnxW+z1bV8MIZHkhApG9trg3NagqruZxkP8UBOy1DYaZVB/OQnbY4N6xb+jErHapzg6XiLUph73mi1/7YJjv5+llFpHGYwXZ1zZdBG4YM+ZJYAhG1yxyYut52146l2irw5Fh+Kwus=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
