travis:
  secure:
    BINSTAR_TOKEN: PVQ22sDp6W0+WtjprJn035Jz2cKBzScFbtiKjrQuPreggYx2SCp7OckM28rn+JPs6AMefJfBDLDDqLMfCRO575Nplm8txI7pbEl33IiJbLWmp9NbjJUgsmecM8BZ5YNt7ym1owbgDLU0beEZbpaPsvc7pJPnP9sBPavF8NIGmPOs/kmRFTVRuyy0/KgX8XyR0Mk19ngJ9Sm/OTx/jEb1JKPEYnu1j9dIz4FXnes0hvUT7fqrQXOQWBrnhTEHWgWynwMN1b1dr4Q1l87ZF33FhAcdjjGCZ9gzxdP7nb8WTO3piHi15cpg444fwyY9uQI+97LxMpkUjd/9+o9AjKUFhpjhzoSA4KdS8pmLO/Ua2Ks+9/1nRGl2R/0hh5hxChySLQZkqRAvF5YmVtMxnQTaOg6s7xBshMklWyoo498whSL4SHhgq7jwTstdUmn4ngsz4fRQCDkTTGJz6JZNyCgl9951hHmjFaUJSN84cJ/9m63zgTW3TdpRf5xiuFRRjRP+2ByZHcRuR94Qt7pzkvCd4OP5OXzm+cfNEJGHsDUbzAhKiah8NbM8c5WjzCW9WmBQ0Tx/4ZKAwXE8DJtH9BbH3AfSsi3O3rmT3bxIAuksRfZe0ijevbL9DTN9rOmeDejA2NIwzJREu51C4D2iaC2zNkh7C+3oL1UNK2hvBJO6z28=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
