travis:
  secure:
    BINSTAR_TOKEN: O4POLXdYUCfWv99xhQRo6o7w22flAmeYNzIt1RIPnt1MsJbV8VmaTs2KhEaCLuia9fWGnWZ2miiQbuv+mlzyGhTp5C+0YU9VURBiZtGjDnbL8K71O8Kom7VurQ1RFUNpmAfQ3za2qmiAMTg9zA7dK3smWB7XrLCQzLjZjllShP8MgGiqO232GaQq70AKpH7gly5am9hM7tVjctVEv2tc6s4F+qpd+YxWul/CzQEhIWe6472rvkX+4zBIlNoNJxQQLufBHxZwk+q+RIb+ZwZS6WSNfJGW5rm1Jpq9mY+CMYh2MXunWh69qeLs3W+mndE2Lwgl3LePVYYlCWf5QrL/gENAM28ap2LZnhFqw7KqqzDCti5iPwWfnDmBG0MxFXg5+BMMQ9WiE7Cvle/4HjU3ydp09no5mRsbWzV3P6rFrhUQ1blpf5LtU9mjUvsbaCLkP8dUhhnOBeZWtrnDpooq1qY4FznwcPGgMWEvmG8VR36ifNi2Af3UwY1mVH4+n0MuLxLJ/pVltV3fXCIkFfGqEUiE8RMCIk81tPWiZcx4KcQfdhGtwA9MDmAgQmWkeGI66ICS5rNB1zzAgtqFOYhp7adl2C+jq6Gf4yOZist0tw708EDx267pomtj4uSDvfEgc1PGTtfpcE8AU8IZCbPSZX5WovP2/jC2SDZevnRfGik=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
