travis:
  secure:
    BINSTAR_TOKEN: Wm/Hd3sMhkDm0/SSWv851Gum4rRtpoH9abMaCqm36jS+zhl9HjdupFXvDASv293YR44FY00jj8GdfdH4SeeZ0EoK3blP2ozn0Om6An+cDYlNN8KQDBQqRME+YCMV2eTadj5ZZ95utk8rA3/RhibrmIS9Pf0rSmD5cZH/q/EhC6ewa5IaKtWhH+nLw9xPtklCVQlcYaXbzFpmwhw9/V6PveiJCFyUePc9CWxBBYyFpWGqicGakyJYmJ3dP73cb9qaDjQdjajUlK1FRpRY9GxW36jt7bvNaPASGbirylCdOOprzYmN8nEWWpyucCnWDE5rP47ILSTaGpbM/Q4XZWhA+vAtQyQhofFgeaT95tQrKjAJzX/R9LWLzlVhE4nYG03DC5GLpy5x5CcOMYJg+BiwasvXAEz0gME4rd8i5A6MaIs5BMv4DZ8/OqX5KM0AecMBfxMTJYaMLaTzigiaYfjJSVZeHsfugimF9nznrtM5CvvMsGfKxAnhmOlxMKcvDWspuEBL1jb7NJs/K8peyDBFT6S0upAX99nehRqmEW4XAa0da7UM6mHHFsYgg+UmXp9hjCDwHQlADHi2gTNN8aqhPtVGgFVnftCtbHaOuQwC/WYK6wtuj3SoS0X73m7XzFLASHFatdJem0Ythvjn1qeE4DLa+LYMKgB6MtezmR9lwjw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
