travis:
  secure:
    BINSTAR_TOKEN: uONLOH6igWVdaGmDBePkXM0P/pMtwLLWQRUKKKjzJ4jK53RDGKHDoFlvimOcajP/r0WKdhqOZMSMvQMNrRKBLeWFuTgTIwcf4Sz/tQ4x7ZDJ7O52I0YvtLSmchZrzP+uFJ+ciQBtwB7L2tr3AgFiE86Widpcicq0tYhmV7po/L9gqxMwt0oiRhM7++DkTpfbBqcPLPwIxlfcAW1JZvsrNLNGonoVlnd3GLs+C91edrhLd0d140nPWVW3zy2jM7TYyOmUFNvT5a6H9BKBDjpRksh0LR+5ypts5FmeZQXm8f5khd+bIiX2WwqsQeGlwPAoaTqrmSDYiG1ADbtkUmk4NFaVHsV9jsabzla6vSW1kcMgtVuuyipBnzfZ66h4e4OhQodGYot2m1GrSOMuqNj4sY/ZjC/P+jx8i/Y6127lKZsOqZVo1U30QJjoTfNMIJBafK+w97lLWEa8jVEogemo+9VxVpZf5pQhJ5TGkc+fUqWnvDyb6/4thSmqCJhhH+fU77K1h3NZ3PgBfkvzoIpzl7OyVb000Qk9dq0We0PNRkO5qcjnmvdgLLSi7DlcgZ0NQZH5gJFwCmrDKP55xn9freIWgPhuJ+J56iyqO/DHxmvxMtcwrcB9Ieltab43vxXjUK5awdCqUxzB4FZNCOaZu3mrbfcJHc2X63ce5qpwGbk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
