travis:
  secure:
    BINSTAR_TOKEN: IzfLbKqoQmvtzRjRPMy/TMb0IhEHXPBHG9P/zC5+3HO7CqfldD9f0MEPQq0woIweQ+gqRj6pXmKq1ZA7i8+Kb3Y9cDdkQa+BJimOgV9ckHS0fANXtODOOWup4YinX0buH3wniFHtWvRUMm0JZS7wo4QaJwyy0L7y4LBds2HDMxtc/azbS5e428uLG+f+3m0vIb0qTQQGIoqjWwbVxSHJSnsksrvhwJpzMpF6MjT18kuBi8l1t+Ov1qcASw4mjNsTyhvty7iKs/Ryljtsh7+xIxQJpqbAHQJiTt+5QVRZO+6fFpKG9J6mgA0ibHWmCODLXM7D+hCEynPw+So0E0we79znQwE6Zc0z/DcZ+W0Xi2VVVv47tCTMlEDoIEwDtdLfCQ42ZvkYWp9aHdOj59hjwfkKaGPHHzWr87ZWzT5mGqS0t3cmltB+R9/Ax5MqZAwmsBEsuo5lQq71XtQ8sQMyuvfRtbO0wKEeV7h/nVQesWc/cQCR7S9CEFVrWQK6hKXdQHs3sKIQrbUL9Vq6Oo83x8UxpRrhDRYjFD75jW9BgEw4y4t+K15lyCSxPskOe8fuuao6Q5WepeVcVxXZAGOlpVgAszSDrcH+IIRmB0BXMLALrd6BP8qfzX4+Bayp+aMMTrJ5gmGNAElNH8gR1JcSkKTpI7Nd3PMmLUGd0cGeBY4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
