travis:
  secure:
    BINSTAR_TOKEN: manlym7CdagCAdR3isqMxxCFLoBn6Hgfr0R7DE/Qaas1PhS4zfkQ3ZiDJ2FcYRYFM9pMmmj/mBhMM+LPCKolzUS+4blZ4NaijfPIy9T//XIpJa+mglG48Mcr3WGkVZ0jUgBe9eQzZhZCtwAhk15qkQM1dluZIvArrN2DDPS2LCvJEya+XWZ7xpQoSEV2vdy3JUQTLEX8t434rRAyHFQiUA7hDV8gVVEtIiN4v5iwEpacXa0FlcNEEaR0j6f8i4Xf68wpkt34aW+e5oLxLFpIGxhNLwslG9nleQEVW0LxF20FUySlswpunS8pY+BTNLj7DuvQ6+vb+SRVuIDjFgkZ9wP3Jg+ERX77B88GIMpa2AYIgCfldN0Ocps1su7Bsf7/XHQd3rvjuPXXEq0regep/tZ8H8KN2ywz0V3XghtEy7eeu0xpOyKTM9Rin59uWAF9h2tJHx9rzhQ1bBnPOF8U7atIHTTR3oPmowHvVJOy8timlUTIiqGcxm60+B+zdJbXp8o1NeZBto0LjsAq80HDWCzV1Hjp1LgaVKiimNuG+z7EanHaimgduGQ3IIhXJcjPOSXqZzPErZyOGF2/4u/2fR/PJz+lG89WgH6AQvEo7k8oVHlcyezO9Kf4RwZI/WWG1mfEMWTTQmsfXJsDjyz/oGwLQYnFxjdK8iIfmV+X+m4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
